services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
  
  api1:
    build:
      context: .
      dockerfile: C:\Users\RyanB\source\repos\RedisWebsocketsPrototype\RedisWebsocketsPrototype.API\Dockerfile
    container_name: api_container1
    ports:
      - "5000:5000"
    depends_on:
      - redis

  api2:
    build:
      context: .
      dockerfile: C:\Users\RyanB\source\repos\RedisWebsocketsPrototype\RedisWebsocketsPrototype.API\Dockerfile
    container_name: api_container2
    ports:
      - "5001:5000"
    depends_on:
      - redis
